### ISSUE TITLE
[error] [function:SHA256 check] ReferenceError: sha256 is not defined

### ISSUE THREAD

**Issue by banek13** [iotacademy/NodeRed_KPN_LoRa#1]
hello

i've done everything as described at page 3. Validating the Token at paragraph "Doing the SHA256 check", but when i run Test Uplink from KPN developer portal the error occurs:
[error] [function:SHA256 check] ReferenceError: sha256 is not defined

**Comment by DentIoT** [comment]
Hi Banek, 

Good to hear you're busy with the Node-RED! Did you manage to resolve the issue yet? Please validate that you got the LRC_AS_Key from you account settings in de developer portal (top right person icon and then click use token authentication and copy the AS KEY underneath it. Otherwise, at the bottom or exercise 3, use the 'complete implementation' link to past the complete solution at once. To do this, go to the link, copy the long line with code, go to node-red, top right use menu > import > via clipboard> paste there. It should give you the complete flow at once. Make sure you still enter your AS KEY at parse lora data.
Another idea would be to use postman and see what response comes from there.

hope this helps
